apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluent.conf: |-
    <system>
     log_level debug  # Adjust the log level as needed
    </system>

    <source>
     @type tail
     path /var/log/containers/java-app*.log
     exclude_path ["/var/log/containers/fluentd*"]
     pos_file /var/log/fluentd-containers.log.pos
     tag kube.*
     <parse>
     @type regexp
      expression /^(?<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+Z) (stdout|stderr) [A-Z] (?<log>{.*})$/
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      time_key time
    </parse>
    </source>
    
    <filter kube.**>
     @type kubernetes_metadata
    </filter>
    

    
    
    <match kube.**>
     @type elasticsearch
     host elasticsearch.logging
     port 9200
     scheme http
     ssl_verify false
     
    
     logstash_format true
     logstash_prefix logstash
     logstash_dateformat %Y.%m.%d  # Adjust the date format as needed
     <buffer>
       @type file
       path /var/log/fluentd-buffer
       flush_interval 5s
     </buffer>
    <format>
       @type single_value
       message_key log
     </format>
     log_level debug  # Set log level to debug
    </match>
   
