apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: confluent
data:
  fluent.conf: |
    <source>
      @type tail
     path /var/log/containers/*kafka-0*.log
      tag kafka.logs
     <parse>
    @type json
    json_parser json
     </parse>
    </source>

    <filter kafka.logs>
       @type parser
        key_name log
        reserve_data true
        <parse>
          @type json
          json_parser json
        </parse>
    </filter>
    
    <filter kafka.logs>
     @type kubernetes_metadata
    </filter>

    <match kafka.logs>
       @type elasticsearch
        host elasticsearch.confluent
        port 9200
        logstash_format true
        include_tag_key true
        tag_key @log_name
        flush_interval 10s
        <buffer>
          flush_thread_count 2
          flush_interval 10s
          retry_type exponential_backoff
          retry_forever
          overflow_action block
        </buffer>
        <format>
          @type json
        </format>
        log_level debug  # Set log level to debug
    </match>
